# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
path = open('clean_weather.csv')

weather_df = pd.read_csv(path)

weather_df.head()

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Tupik,54.43,119.93,240.21,77,0,1.65,RU,1607897161
1,1,Dunedin,-45.87,170.50,287.04,67,91,10.28,NZ,1607897186
2,2,Bluff,-46.60,168.33,286.48,74,100,4.02,NZ,1607896911
3,3,Hamilton,39.18,-84.53,278.78,75,90,1.50,US,1607897186
4,4,Morehead,37.27,-87.18,280.27,73,90,1.50,US,1607897186

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
gmaps.configure(api_key=g_key)

# Store 'Lat' and 'Lng' into  locations 
locations = weather_df[["Lat", "Lng"]].astype(float)

humidity = weather_df["Humidity"]

In [4]:
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 3)
fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [12]:
#ideal_weather_df = weather_df.loc[(weather_df["Wind Speed"] <= 10) & (weather_df["Cloudiness"] == 0) & (weather_df["Max Temp"] >= 70) & (weather_df["Max Temp"] <= 80)].dropna()

ideal_weather_df = weather_df.loc[weather_df["Wind Speed"] <= 10]
                                   
ideal_weather_df = weather_df.loc[weather_df["Max Temp"] >= 70]

ideal_weather_df = weather_df.loc[weather_df["Max Temp"] <= 80]

ideal_weather_df = weather_df.loc[weather_df["Cloudiness"] == 0]

ideal_weather_df

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Tupik,54.43,119.93,240.21,77,0,1.65,RU,1607897161
10,10,Puerto Ayora,-0.74,-90.35,298.18,65,0,6.70,EC,1607897187
20,20,Makkah al Mukarramah,21.43,39.83,296.32,60,0,0.99,SA,1607896981
29,29,Bukachacha,52.98,116.92,246.53,76,0,1.56,RU,1607897190
48,48,Chapulhuac√°n,21.17,-98.90,297.61,68,0,2.06,MX,1607897192
...,...,...,...,...,...,...,...,...,...,...
528,528,R√≠o Tercero,-32.17,-64.11,298.15,22,0,1.79,AR,1607897266
533,533,Fort-Shevchenko,44.51,50.26,273.27,91,0,10.19,KZ,1607897267
539,539,Zaranj,30.97,61.88,274.15,47,0,9.30,AF,1607897268
547,547,Marzuq,14.40,46.47,283.16,48,0,1.20,YE,1607897269
549,549,Lingu√®re,15.40,-15.12,298.15,38,0,2.10,SN,1607897270

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [26]:
#Create the hotel_df variable
hotel_df = ideal_weather_df
#hotel_df.insert(0,'Hotel Name2','')
hotel_df

,Hotel Name2,Roll Number,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name,foo
0,,,0,Tupik,54.43,119.93,240.21,77,0,1.65,RU,1607897161,,
10,,,10,Puerto Ayora,-0.74,-90.35,298.18,65,0,6.70,EC,1607897187,,
20,,,20,Makkah al Mukarramah,21.43,39.83,296.32,60,0,0.99,SA,1607896981,,
29,,,29,Bukachacha,52.98,116.92,246.53,76,0,1.56,RU,1607897190,,
48,,,48,Chapulhuac√°n,21.17,-98.90,297.61,68,0,2.06,MX,1607897192,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,,,528,R√≠o Tercero,-32.17,-64.11,298.15,22,0,1.79,AR,1607897266,,
533,,,533,Fort-Shevchenko,44.51,50.26,273.27,91,0,10.19,KZ,1607897267,,
539,,,539,Zaranj,30.97,61.88,274.15,47,0,9.30,AF,1607897268,,
547,,,547,Marzuq,14.40,46.47,283.16,48,0,1.20,YE,1607897269,,
549,,,549,Lingu√®re,15.40,-15.12,298.15,38,0,2.10,SN,1607897270,,

In [ ]:
params = {
    "radius": 5000,
    "types": "lodging",
    "keyword": "Hotel",
    "key": gkey}

#base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure