# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [14]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [15]:
path = open('clean_weather.csv')

weather_df = pd.read_csv(path)

weather_df.head()

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Lavrentiya,65.58,-171.00,15.96,96,100,14.14,RU,1608080005
1,1,Puerto Ayora,-0.74,-90.35,72.00,90,98,5.01,EC,1608079988
2,2,Atuona,-9.80,-139.03,78.87,77,6,17.63,PF,1608080005
3,3,Pevek,69.70,170.31,11.71,91,100,8.52,RU,1608080005
4,4,Almeirim,-1.52,-52.58,75.38,90,58,2.80,BR,1608080005

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [16]:
gmaps.configure(api_key=g_key)

# Store 'Lat' and 'Lng' into  locations 
locations = weather_df[["Lat", "Lng"]].astype(float)

humidity = weather_df["Humidity"]

In [17]:
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 3)
fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [21]:
#ideal_weather_df = weather_df.loc[(weather_df["Wind Speed"] <= 10) & (weather_df["Cloudiness"] == 0) & (weather_df["Max Temp"] >= 70) & (weather_df["Max Temp"] <= 80)].dropna()

ideal_weather_df = weather_df.loc[weather_df["Wind Speed"] <= 10]
                                   
ideal_weather_df = weather_df.loc[weather_df["Max Temp"] >= 70]

ideal_weather_df = weather_df.loc[weather_df["Max Temp"] <= 80]

ideal_weather_df = weather_df.loc[weather_df["Cloudiness"] == 0]

ideal_weather_df = ideal_weather_df.dropna(how='any')

ideal_weather_df

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
8,8,TrÃªs Barras,-26.11,-50.32,64.58,97,0,2.24,BR,1608080006
12,12,Punta Arenas,-53.15,-70.92,48.09,66,0,24.16,CL,1608080006
15,15,Geraldton,-28.77,114.60,75.20,44,0,12.75,AU,1608080007
16,16,Narsaq,60.92,-46.05,39.20,35,0,27.51,GL,1608080007
33,33,Saldanha,-33.01,17.94,60.80,72,0,12.75,ZA,1608079817
...,...,...,...,...,...,...,...,...,...,...
533,533,Taoudenni,22.68,-3.98,66.24,26,0,7.94,ML,1608080089
534,534,Melilla,35.29,-2.94,51.64,76,0,2.24,ES,1608080089
536,536,Rancho Palos Verdes,33.74,-118.39,60.48,68,0,11.10,US,1608080089
541,541,Yarim,14.30,44.38,45.21,53,0,1.97,YE,1608080090
544,544,Faya,18.39,42.45,50.00,70,0,2.19,SA,1608080090

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [22]:
#Create the hotel_df variable
hotel_df = ideal_weather_df
hotel_df.insert(0,'Hotel Name','')
hotel_df

,Hotel Name,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
8,,8,TrÃªs Barras,-26.11,-50.32,64.58,97,0,2.24,BR,1608080006
12,,12,Punta Arenas,-53.15,-70.92,48.09,66,0,24.16,CL,1608080006
15,,15,Geraldton,-28.77,114.60,75.20,44,0,12.75,AU,1608080007
16,,16,Narsaq,60.92,-46.05,39.20,35,0,27.51,GL,1608080007
33,,33,Saldanha,-33.01,17.94,60.80,72,0,12.75,ZA,1608079817
...,...,...,...,...,...,...,...,...,...,...,...
533,,533,Taoudenni,22.68,-3.98,66.24,26,0,7.94,ML,1608080089
534,,534,Melilla,35.29,-2.94,51.64,76,0,2.24,ES,1608080089
536,,536,Rancho Palos Verdes,33.74,-118.39,60.48,68,0,11.10,US,1608080089
541,,541,Yarim,14.30,44.38,45.21,53,0,1.97,YE,1608080090
544,,544,Faya,18.39,42.45,50.00,70,0,2.19,SA,1608080090

In [25]:
params = {
    "radius": 5000,
    "types": "lodging",
    "keyword": "Hotel",
    "key": g_key}

ideal_cities = len(ideal_weather_df)

#for x in ideal_cities.iterrows():
#    lat = x['Lat']
    

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

AttributeError: 'int' object has no attribute 'iterrows'

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure